name: gap
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.6=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - pytorch=2.0.1=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py38h06a4308_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.0.2=py38_cu117
  - torchtriton=2.0.0=py38
  - torchvision=0.15.2=py38_cu117
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
    - absl-py==2.1.0
    - aiofiles==24.1.0
    - anyio==4.5.2
    - argcomplete==3.5.3
    - attrs==24.3.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.12.3
    - boto3==1.35.90
    - botocore==1.35.90
    - brotli==1.1.0
    - cachetools==5.5.0
    - cmake==3.30.4
    - contourpy==1.1.1
    - cycler==0.12.1
    - cython==3.0.12
    - dacite==1.7.0
    - decord==0.6.0
    - deprecated==1.2.15
    - dill==0.3.9
    - dnspython==2.6.1
    - easydict==1.13
    - einops==0.8.0
    - exceptiongroup==1.2.2
    - fiftyone==0.25.2
    - fiftyone-brain==0.17.0
    - fiftyone-db==1.1.5
    - fonttools==4.54.1
    - ftfy==6.2.3
    - future==1.0.0
    - glob2==0.7
    - google-auth==2.36.0
    - google-auth-oauthlib==1.0.0
    - graphql-core==3.2.5
    - grpcio==1.67.1
    - h11==0.14.0
    - h2==4.1.0
    - h5py==3.11.0
    - hpack==4.0.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - humanize==4.10.0
    - hypercorn==0.17.3
    - hyperframe==6.0.1
    - imageio==2.35.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - inflate64==1.0.0
    - jmespath==1.0.1
    - joblib==1.4.2
    - jsonlines==4.0.0
    - kaleido==0.2.1
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lit==18.1.8
    - markdown==3.7
    - matplotlib==3.7.5
    - mongoengine==0.24.2
    - motor==3.5.3
    # - multiscaledeformableattention==1.0
    - multivolumefile==0.2.3
    - oauthlib==3.2.2
    - opencv-contrib-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - packaging==24.1
    - pandas==2.0.3
    - plotly==5.24.1
    - pprintpp==0.4.0
    - priority==2.0.0
    - protobuf==5.28.3
    - psutil==6.1.1
    - py7zr==0.22.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybcj==1.0.2
    - pycryptodomex==3.21.0
    - pydash==8.0.4
    - pymongo==4.8.0
    - pyparsing==3.1.4
    - pyppmd==1.1.0
    - python-dateutil==2.9.0.post0
    - pytz==2024.2
    - pywavelets==1.4.1
    - pyyaml==6.0.2
    - pyzstd==0.16.2
    - rarfile==4.2
    - regex==2024.9.11
    - requests-oauthlib==2.0.0
    - retrying==1.3.4
    - rsa==4.9
    - s3transfer==0.10.4
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - six==1.16.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - soupsieve==2.6
    - sse-starlette==0.10.3
    - sseclient-py==1.8.0
    - starlette==0.44.0
    - strawberry-graphql==0.138.1
    - tabulate==0.9.0
    - taskgroup==0.2.1
    - tenacity==9.0.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - texttable==1.7.0
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - tomli==2.2.1
    - tqdm==4.66.5
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - tzlocal==5.2
    - universal-analytics-python3==1.1.1
    - urllib3==1.26.20
    - voxel51-eta==0.12.7
    - wcwidth==0.2.13
    - werkzeug==3.0.6
    - wrapt==1.17.0
    - wsproto==1.2.0
    - xmltodict==0.14.2
    - zipp==3.20.2
prefix: /home/yayun502/anaconda3/envs/gap
